import type { CollectionConfig } from "./types";

export const autoConfig: CollectionConfig = {
  label: "automobile",
  moduleSlug: "automobiles",
  table: "automobiles",
  alias: "a",
  imagesTable: "auto_images",
  imageFkColumn: "auto_id",
  valuationsTable: "auto_valuations",
  valuationFkColumn: "auto_id",
  validCategories: ["collection", "household"],
  fields: [
    { name: "brand", required: true, trim: true },
    { name: "model", required: true, trim: true },
    { name: "year", type: "integer" },
    { name: "description", trim: true },
    { name: "trim_level", trim: true },
    { name: "engine", trim: true },
    { name: "transmission", trim: true },
    { name: "mileage", type: "integer" },
    { name: "condition" },
    { name: "body_style", trim: true },
    { name: "color", trim: true },
    { name: "vin", trim: true },
    { name: "purchase_price", type: "number" },
    { name: "purchase_date", type: "date" },
    { name: "purchase_source", trim: true },
    { name: "notes", trim: true },
    { name: "insure", type: "boolean" },
    { name: "specs", type: "jsonb" },
    { name: "listing_intro", trim: true },
    { name: "listing_footer", trim: true },
    { name: "package_weight_lb", type: "number" },
    { name: "package_length_in", type: "number" },
    { name: "package_width_in", type: "number" },
    { name: "package_height_in", type: "number" },
    { name: "listing_price", type: "number" },
  ],
  conditionRequired: false,
  patchSetUpdatedAt: true,
  forceDynamic: true,
  specTemplate: [
    "Engine",
    "Horsepower",
    "Torque",
    "Drivetrain",
    "Transmission",
    "0-60 mph",
    "Top Speed",
    "Curb Weight",
    "Fuel Economy",
    "Production Numbers",
    "Exterior Color",
    "Interior",
    "Country of Manufacture",
  ],
};
