import type { CollectionConfig } from "./types";

export const guitarConfig: CollectionConfig = {
  label: "guitar",
  moduleSlug: "guitars",
  table: "guitar_items",
  alias: "gi",
  imagesTable: "guitar_images",
  imageFkColumn: "guitar_item_id",
  valuationsTable: "guitar_valuations",
  valuationFkColumn: "guitar_item_id",
  validCategories: ["electric-guitars", "acoustic-guitars", "amplifiers", "pedals"],
  fields: [
    { name: "brand", required: true, trim: true },
    { name: "model", required: true, trim: true },
    { name: "year", type: "integer" },
    { name: "serial_number", trim: true },
    { name: "condition", required: true },
    { name: "purchase_price", type: "number" },
    { name: "purchase_source", trim: true },
    { name: "color_finish", trim: true },
    { name: "short_description", trim: true },
    { name: "link", trim: true },
    { name: "notes", trim: true },
    { name: "insure", type: "boolean" },
    { name: "specs", type: "jsonb" },
    { name: "listing_intro", trim: true },
    { name: "listing_footer", trim: true },
    { name: "package_weight_lb", type: "number" },
    { name: "package_length_in", type: "number" },
    { name: "package_width_in", type: "number" },
    { name: "package_height_in", type: "number" },
    { name: "listing_price", type: "number" },
  ],
  conditionRequired: true,
  patchSetUpdatedAt: false,
  forceDynamic: false,
  specTemplate: [
    "Body Wood",
    "Top Wood",
    "Neck Wood",
    "Fretboard",
    "Number of Frets",
    "Scale Length",
    "Pickups",
    "Electronics",
    "Bridge",
    "Tuners",
    "Nut Width",
    "Country of Manufacture",
    "Weight",
  ],
};
