import type { CollectionConfig } from "./types";

export const iodConfig: CollectionConfig = {
  label: "item-of-distinction",
  moduleSlug: "iod",
  table: "items_of_distinction",
  alias: "i",
  imagesTable: "iod_images",
  imageFkColumn: "iod_id",
  valuationsTable: "iod_valuations",
  valuationFkColumn: "iod_id",
  validCategories: ["fine-art", "memorabilia", "collectibles", "jewelry", "other"],
  fields: [
    { name: "item_type", trim: true, maxLength: 255 },
    { name: "brand", trim: true, maxLength: 255 },
    { name: "short_description", required: true, trim: true, maxLength: 500 },
    { name: "long_description", trim: true },
    { name: "year", type: "integer" },
    { name: "condition" },
    { name: "purchase_price", type: "number", precision: 12, scale: 2 },
    { name: "purchase_date", type: "date" },
    { name: "purchase_source", trim: true, maxLength: 255 },
    { name: "provenance", trim: true },
    { name: "notes", trim: true },
    { name: "insure", type: "boolean" },
    { name: "specs", type: "jsonb" },
    { name: "listing_intro", trim: true },
    { name: "listing_footer", trim: true },
    { name: "package_weight_lb", type: "number" },
    { name: "package_length_in", type: "number" },
    { name: "package_width_in", type: "number" },
    { name: "package_height_in", type: "number" },
    { name: "listing_price", type: "number" },
  ],
  imageOriginalNameMaxLength: 500,
  conditionRequired: false,
  patchSetUpdatedAt: true,
  forceDynamic: true,
  specTemplate: [
    "Maker/Artist",
    "Medium/Materials",
    "Dimensions",
    "Edition/Numbering",
    "Signature/Markings",
    "Year/Period",
    "Origin",
    "Certificate of Authenticity",
    "Framing/Mounting",
  ],
};
