import type { CollectionConfig } from "./types";

export const watchConfig: CollectionConfig = {
  label: "watch",
  moduleSlug: "watches",
  table: "watch_items",
  alias: "wi",
  imagesTable: "watch_images",
  imageFkColumn: "watch_item_id",
  valuationsTable: "watch_valuations",
  valuationFkColumn: "watch_item_id",
  validCategories: ["luxury-watches", "sport-watches", "dress-watches", "vintage-watches"],
  fields: [
    { name: "brand", required: true, trim: true },
    { name: "model", required: true, trim: true },
    { name: "year", type: "integer" },
    { name: "reference_number", trim: true },
    { name: "case_diameter", trim: true },
    { name: "serial_number", trim: true },
    { name: "condition", required: true },
    { name: "purchase_price", type: "number" },
    { name: "purchase_source", trim: true },
    { name: "dial_color", trim: true },
    { name: "country_of_manufacture", trim: true },
    { name: "movement", trim: true },
    { name: "bracelet_material", trim: true },
    { name: "case_material", trim: true },
    { name: "short_description", trim: true },
    { name: "link", trim: true },
    { name: "notes", trim: true },
    { name: "insure", type: "boolean" },
    { name: "specs", type: "jsonb" },
    { name: "listing_intro", trim: true },
    { name: "listing_footer", trim: true },
    { name: "package_weight_lb", type: "number" },
    { name: "package_length_in", type: "number" },
    { name: "package_width_in", type: "number" },
    { name: "package_height_in", type: "number" },
    { name: "listing_price", type: "number" },
  ],
  conditionRequired: true,
  patchSetUpdatedAt: false,
  forceDynamic: false,
  specTemplate: [
    "Movement",
    "Caliber",
    "Power Reserve",
    "Case Material",
    "Case Diameter",
    "Case Thickness",
    "Lug Width",
    "Crystal",
    "Dial Color",
    "Bezel",
    "Bracelet/Strap",
    "Water Resistance",
    "Complications",
    "Country of Manufacture",
  ],
};
